server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          # Đã bổ sung ".git" ở cuối URI và sửa tên nhánh mặc định thành "main"
          uri: https://github.com/foodx/config-repo.git
          default-label: main
