<<<<<<< HEAD
server:
  port: 8083

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://localhost:3306/medicare_appointment_db
    username: root
    password: luyen123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
=======
server:
  port: 8083

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://localhost:3306/medicare_appointment_db
    username: root
    password: luyen123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
>>>>>>> 4101676851925098dd510ffc36d26f9bc968f423
        dialect: org.hibernate.dialect.MySQLDialect