server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/finbank_account?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: luyen123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
